# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fcdad070b35847f0d0cc33c9a48470a31d2ce98801c6799640382cd34d37f5e3c72972324c5858cd83690ed6797ebaf0596de664a3034b8eed991bd7289e7a6

test:
  secret_key_base: 3810d88322f86ce6296809eb9fec5353518480c5b1e6214f02faa532039b127d2f3a64c386cdfec794acfa2dc82b966d37ea590a28d0a3cf3881999691a31653

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
